### ISSUE TITLE
Popraviti E-Mail template pri registraciji novog korisnika

### ISSUE THREAD

**Issue by mahmuzicamel** [ITTECH10/technical_inspection_frontend#14]
E-Mail Template mora izgledati kao na slici:

![image](https://user-images.githubusercontent.com/476067/160137181-97a36f2e-248b-4f40-a363-309bbf9cbb47.png)

Ubaciti slijedeci text:

**SE Carmanagement | Ihr Profil wurde erstellt**

Vielen Dank, dass Sie sich dazu entschieden haben, die Verwaltung Ihres Fuhrparks an uns als zuverlässigen Partner abzugeben. Wir von SE-Carmanagement übernehmen sämtliches Fahrzeug- und Fuhrparkmanagement.

Mit dieser E-Mail übermitteln wir Ihnen wie gewünscht Ihre persönlichen Login Daten: für https://app.se-carmanagement.de/

**E-Mail**: {{e-mail}}
**Einmalpasswort**: {{password}}

Wir managen Ihren Fuhrpark, damit Sie sich um Ihr Kerngeschäft kümmern können.

Herzlich Willkommen bei Ihrem Team von

logo

Geltinger Str. 23
85652 Pliening

Tel: 08121 / 22 43 8 - 22
Fax: 08121 / 22 43 8 - 10

[mail: info@se-carmanagement.de](mailto:info@secarmanagament.de)
[www.se-carmanagement.de](https://www.se-carmanagement.de/)

Bitte beachten Sie, dass diese Information ausschließlich für den/die Adressaten bestimmt ist und daher vertraulich oder gesetzlich geschützte Informationen enthalten kann. Sollten Sie nicht der bestimmungsgemäße Adressat sein, bitten wir Sie den Absender darauf hinzuweisen und im Anschluss diese Mail umgehend zu vernichten. Anderen als dem bestimmungsgemäßen Adressaten ist es untersagt, diese E-Mail zu lesen, zu speichern, weiterzuleiten oder ihren Inhalt auf welche Weise auch immer zu verwenden. Wir verwenden aktuelle Virenschutzprogramme. Für Schäden, die dem Empfänger durch von uns zugesandte mit Viren befallene E-Mails entstehen, schließen wir jede Haftung aus.

--
Schneider & Eberhart Carmanagement GbR Gesellschafter: Maria Schneider und Wolfgang Eberhart

**Comment by ITTECH10** [comment]
#14 should be tested

**Comment by mahmuzicamel** [comment]
ok
