### ISSUE TITLE
Template: "Ihre KFZ-Finanzierung läuft in drei Monaten aus!" mora sadrzavati slijedeci text 

### ISSUE THREAD

**Issue by mahmuzicamel** [ITTECH10/technical_inspection_frontend#15]
Subject: **Ihre KFZ-Finanzierung läuft in drei Monaten aus!**

CONDITIONAL: 
if(male) = "Sehr geehrter Herr " {name} {surname}
if(female) = "Sehr geehrte Frau " {name} {surname}

die Vertragslaufzeit Ihres Fahrzeuges **{Hersteller} {Modell}** mit Kennzeichen **{Kennzeichen}** endet demnächst.

Da die Automobilwelt im Wandel steht und Sie mit längeren Lieferzeiten rechnen müssen, würden wir gerne mit Ihnen zeitnah einen Termin vereinbaren, um die Zukunft Ihres Fahrzeuges zu besprechen.

Ob Rückgabe, Anschlussvertrag bei der Bank oder Fahrzeugwechsel, wir finden für Sie den optimalen Weg und begleiten Sie dabei. Sichern Sie sich schon jetzt die besten Konditionen und melden sich bei uns!

Herzlich Willkommen bei Ihrem Team von

logo

Geltinger Str. 23
85652 Pliening

Tel: 08121 / 22 43 8 - 22
Fax: 08121 / 22 43 8 - 10

[mail: info@se-carmanagement.de](mailto:info@secarmanagament.de)
[www.se-carmanagement.de](https://www.se-carmanagement.de/)

Bitte beachten Sie, dass diese Information ausschließlich für den/die Adressaten bestimmt ist und daher vertraulich oder gesetzlich geschützte Informationen enthalten kann. Sollten Sie nicht der bestimmungsgemäße Adressat sein, bitten wir Sie den Absender darauf hinzuweisen und im Anschluss diese Mail umgehend zu vernichten. Anderen als dem bestimmungsgemäßen Adressaten ist es untersagt, diese E-Mail zu lesen, zu speichern, weiterzuleiten oder ihren Inhalt auf welche Weise auch immer zu verwenden. Wir verwenden aktuelle Virenschutzprogramme. Für Schäden, die dem Empfänger durch von uns zugesandte mit Viren befallene E-Mails entstehen, schließen wir jede Haftung aus.

--
Schneider & Eberhart Carmanagement GbR Gesellschafter: Maria Schneider und Wolfgang Eberhart

**Comment by ITTECH10** [comment]
#15 should be tested

**Comment by mahmuzicamel** [comment]
Nije dobro. Za "Gospodje" treba da bude "Sehr geehrte Frau " a za "Gospodine" treba da stoji "Sehr geehrte**r** Herr"

**Comment by mahmuzicamel** [comment]
OK
